kind: pipeline
name: KangX Build

steps:
- name: Checkout build submodules
  image: archlinux:latest
  commands:
  - pacman -Sy --noconfirm git unzip wget jdk8-openjdk go ninja python make diffutils patch
  - git submodule update --init --recursive --depth 1
  - mkdir -p ~/Android/cmdline-tools
  - cd ~/Android/cmdline-tools
  - wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -O commandlinetools.zip
  - unzip commandlinetools.zip
  - cd ../..
  - export ANDROID_HOME=~/Android
  - export PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$PATH
  - yes | sdkmanager 'ndk;21.3.6528147'
  - yes | sdkmanager --licenses
  - export NDK=$ANDROID_HOME/ndk/21.3.6528147
  - cd /drone/src/TMessagesProj/jni
  - export NINJA_PATH=/usr/bin/ninja
  - ./build_ffmpeg_clang.sh
  - ./patch_ffmpeg.sh
  - ./patch_boringssl.sh
  - ./build_boringssl.sh
  - cd ../..
  - USE_SPLITBUILD=1 ./gradlew assembleRelease
  environment:
    APP_ID:
      from_secret: APP_ID
    APP_HASH:
      from_secret: APP_HASH
    ALIAS_NAME:
      from_secret: ALIAS_NAME
    ALIAS_PASS:
      from_secret: ALIAS_PASS
    KEYSTORE_PASS:
      from_secret: KEYSTORE_PASS
