kind: pipeline
name: KangX Build

steps:
- name: Checkout build submodules
  image: runmymind/docker-android-sdk:ubuntu-standalone
  commands:
  - git submodule update --init --recursive

- name: Install runtime dependencies
  image: runmymind/docker-android-sdk:ubuntu-standalone
  commands:
  - ls $ANDROID_HOME/ndk/
  - apt update
  - apt install -y golang ninja-build python3-pip

- name: Patch and build ffmpeg
  image: runmymind/docker-android-sdk:ubuntu-standalone
  commands:
  - export NDK=$ANDROID_HOME/ndk/21.3.6528147
  - cd TMessagesProj/jni
  - ./build_ffmpeg_clang.sh
  - ./patch_ffmpeg.sh

- name: Patch and build boringssl
  image: runmymind/docker-android-sdk:ubuntu-standalone
  commands:
  - export NDK=$ANDROID_HOME/ndk/21.3.6528147
  - cd TMessagesProj/jni
  - ./patch_boringssl.sh
  - ./build_boringssl.sh

- name: Build
  image: runmymind/docker-android-sdk:ubuntu-standalone
  commands:
  - USE_SPLITBUILD=1 ./gradlew assembleRelease
  environment:
    APP_ID:
      from_secret: APP_ID
    APP_HASH:
      from_secret: APP_HASH
    ALIAS_NAME:
      from_secret: ALIAS_NAME
    ALIAS_PASS:
      from_secret: ALIAS_PASS
    KEYSTORE_PASS:
      from_secret: KEYSTORE_PASS
