version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          name: Checkout git submodules
          command: |
            git submodule update --init --recursive --depth 1
      - run:
          name: Build and patch ffmpeg
          command: |
            cd TMessagesProj/jni
            ./build_ffmpeg_clang.sh
            ./patch_ffmpeg.sh
      - run:
          name: Patch and build boringssl
          command: |
            cd TMessagesProj/jni
            ./patch_boringssl.sh
            ./build_boringssl.sh
      - run:
          name: Build the app
          command: USE_SPLITBUILD=1 ./gradlew assembleRelease
